[kbsnews]
title = "KBS뉴스 ─ 네이버TV"
url = "https://tv.naver.com/kbsnews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[imnews]
title = "MBC뉴스 ─ 네이버TV"
url = "https://tv.naver.com/imnews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[sbsnews8]
title = "SBS뉴스 ─ 네이버TV"
url = "https://tv.naver.com/sbsnews8/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[jtbcnews]
title = "JTBC뉴스 ─ 네이버TV"
url = "https://tv.naver.com/jtbcnews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[yonhapnewstv]
title = "연합뉴스TV ─ 네이버TV"
url = "https://tv.naver.com/yonhapnewstv/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[ytnnews24]
title = "뉴스는 YTN ─ 네이버TV"
url = "https://tv.naver.com/ytnnews24/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[tvchosunnews]
title = "TV조선 뉴스 ─ 네이버TV"
url = "https://tv.naver.com/tvchosunnews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[channelanews]
title = "채널A뉴스 ─ 네이버TV"
url = "https://tv.naver.com/channelanews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[mbnnews]
title = "MBN 뉴스 ─ 네이버TV"
url = "https://tv.naver.com/mbnnews/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
